.gitignore
.travis.yml
build-deps.sh
codebuild/common-linux.sh
codebuild/common-macos.sh
codebuild/linux-clang3-x64.yml
codebuild/linux-clang6-x64.yml
codebuild/linux-gcc-4x-x64.yml
codebuild/linux-gcc-4x-x86.yml
codebuild/linux-gcc-5x-x64.yml
codebuild/linux-gcc-6x-x64.yml
codebuild/linux-gcc-7x-x64.yml

CI work, preparation for release

---

.gitignore
.travis.yml
aws_crt/io.py
aws_crt/iot.py
aws_crt/mqtt.py
build-deps.sh
codebuild/common-linux.sh
codebuild/common-macos.sh
codebuild/common-windows.bat
codebuild/linux-clang3-x64.yml
codebuild/linux-clang6-x64.yml
codebuild/linux-gcc-4x-x64.yml
codebuild/linux-gcc-4x-x86.yml
codebuild/linux-gcc-5x-x64.yml
codebuild/linux-gcc-6x-x64.yml
codebuild/linux-gcc-7x-x64.yml
codebuild/windows-msvc-2015-x86.yml
codebuild/windows-msvc-2015.yml
codebuild/windows-msvc-2017.yml
setup.py
source/io.c
source/io.h
source/module.c
source/module.h
source/mqtt_client.c
source/mqtt_client_connection.c
source/mqtt_client_connection.h
test.py

Pairs well with awslabs/aws-c-mqtt#34.

API Updates

---

setup.py
source/module.c
source/module.h
source/mqtt_client_connection.c

Build and runtime fixes

---

build-deps.sh
codebuild/common-linux.sh
codebuild/common-macos.sh
codebuild/common-windows.bat
codebuild/linux-clang6-x64.yml

 Fixes ported from standing up aws-crt-java's CI

---

codebuild/common-linux.sh

moved back to s2n head rev

---

aws_crt/iot.py
aws_crt/mqtt.py
test.py

test.py: return value from on_disconnect to avoid reconnecting

---

source/io.c

client_bootstrap API fixes

---

build-deps.sh

Added s2n to build deps so linux builds will work.

---

setup.py

Allow using pre-installed dependencies

---

aws_crt/mqtt.py
codebuild/linux-clang6-x64.yml
codebuild/linux-gcc-6x-x64.yml
test.py

Merge connection constructor with connect()

---

.gitignore
aws_crt/io.py
aws_crt/mqtt.py
codebuild/common-macos.sh
codebuild/linux-clang3-x64.yml
codebuild/linux-clang6-x64.yml
codebuild/linux-gcc-4x-x64.yml
codebuild/linux-gcc-5x-x64.yml
codebuild/linux-gcc-6x-x64.yml
codebuild/linux-gcc-7x-x64.yml
setup.py
source/module.c
source/module.h
source/mqtt_client_connection.c
source/mqtt_client_connection.h
test.py

- Compatibility with recent aws-c-mqtt API changes (interruption callbacks, etc)
- Functions that had completion-callbacks now return Futures instead.
- Use Python-3-style enums.
- Update aws-c-common, aws-c-io, aws-c-mqtt, s2n dependencies
- Scrubbed over mqtt_client_connection.c, being more careful about refcounts and error-handling.

Callbacks 4 Dayz

---

MANIFEST.in

Forgot to add the aws-c-cal to the Manifest.

---

setup.py

Updated version number.

---

awscrt/mqtt.py
codebuild/ancient-linux-x64.yml
codebuild/common-linux.sh
source/io.c
source/mqtt_client_connection.c
test.py

Additionally updated TLS and MQTT dependencies and applied API changes.

Unit tests in CI

---

setup.py

Fixed CFLAGS and LDFLAGS merging

---

setup.py

updated to v0.2.6

---

codebuild/cd/manylinux1-tee.yml
codebuild/cd/publish_to_prod_pypi.yml
codebuild/cd/publish_to_test_pypi.yml
codebuild/cd/windows-tee.yml
continuous-delivery/build-wheels-osx.sh
setup.py

Updates to CI pipeline.

---

codebuild/cd/manylinux1-tee.yml
codebuild/cd/windows-tee.yml
setup.py

Forgot to mkdir before copying to one.

---

setup.py

You have to do an annotated tag for them to be useful.

---

awscrt/io.py
source/io.c
source/io.h
source/module.c
test.py

Enabled TLS certs/key to be provided as bytes

---

setup.py

Version bump -> v0.2.11

---

MANIFEST.in
awscrt/http.py
elasticurl.py
setup.py
source/http_client_connection.c

Addressed late feedback.

---

awscrt/io.py
setup.py

Python 2 is DDDDUUUUUMMMMMBBBBBB

---

setup.py

Added v0.2.18, v0.2.17 was released without updating setup.py

---

source/http_client_connection.c

Fix extra amount_read param

---

awscrt/io.py
source/http_stream.c
source/io.c
test/test_io.py

Async event-loop-group cleanup

---

awscrt/__init__.py
test/__init__.py
test/test_io.py

Track living NativeResources. Unit tests assert they're all gone.

---

.gitignore
setup.py

Misc build fixes.

---

codebuild/common-linux.sh

CI checks python formatting

---

source/io.c

aws-c-common v0.4.12
aws-c-io v0.4.11
aws-c-mqtt v0.4.7

Update dependencies to latest

---

setup.py

fix python 2

---

codebuild/cd/publish_to_prod_pypi.yml
codebuild/cd/publish_to_test_pypi.yml
continuous-delivery/wait-for-pypi.py

wait for package to be visible in pypi before proceeding

---

awscrt/io.py
awscrt/mqtt.py
source/mqtt_client_connection.c

Implement socket_options paramater for mqtt.connect

---

.gitmodules
awscrt/__init__.py
awscrt/auth.py
setup.py
source/auth.h
source/auth_credentials.c
source/module.c
test/resources/credentials_test
test/test_credentials.py

Only exposing "default chain" and "static" providers for now

aws_credentials_provider binding

---

setup.py
source/mqtt_client_connection.c
test/test_mqtt.py

Also contains PR feedback/fixes from https://github.com/awslabs/aws-crt-python/pull/94

Bumped version for new pypi package

---

awscrt/auth.py
source/auth.h
source/auth_credentials.c
source/auth_signer.c
source/module.c
test/test_auth.py

adapt to auth api changes

---

awscrt/auth.py
awscrt/awsiot_mqtt_connection_builder.py
awscrt/http.py
awscrt/mqtt.py
elasticurl.py
mqtt_test.py
setup.py
source/auth.h
source/auth_signing_config.c
source/module.c
source/mqtt_client_connection.c
test/test_auth.py
test/test_http_client.py
test/test_mqtt.py

Callback kwargs

---

awscrt/awsiot_mqtt_connection_builder.py
awscrt/mqtt.py
setup.py
source/mqtt_client_connection.c

Kwarg bug fixes

---

codebuild/cd/manylinux1-tee.yml
continuous-delivery/build-wheels-manylinux2014-arm.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
continuous-delivery/build-wheels-osx.sh
continuous-delivery/build-wheels-win32.bat
continuous-delivery/build-wheels-win64.bat

Added manylinux2014 and python 3.8 builds.

---

codebuild/cd/manylinux1-tee.yml
continuous-delivery/build-wheels-manylinux2014-arm.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
setup.py

I think trailing whitespace is breaking the codebuild job.

---

awscrt/io.py
source/io.c
test/__init__.py
test/test_auth.py
test/test_io.py
test/test_mqtt.py

Incorporate API changes from https://github.com/awslabs/aws-c-io/pull/215
🎉🎉🎉 This fixes the longstanding crashes Windows-only crashes in our unit tests! 🎉🎉🎉
😭😭😭 But the Elasticurl integration-tests still fail during shutdown (windows only).  😭😭😭
I'll chase down the newly exposed crashes in a separate PR

bootstrap-shutdown-cb: python edition

---

awscrt/mqtt.py

*Issue #, if available:* #120 
*Description of changes:* Ported fix from #121 to allow GitHub Actions to run.

Fixed incorrect named argument to on_connection_resumed callback

---

.builder/actions/aws_crt_python.py
.github/workflows/ci.yml
builder.json

Builder update

---

.github/workflows/ci.yml

Added VC14 CI

---

awscrt/mqtt.py
setup.py
source/mqtt_client_connection.c

These values weren't being passed down to aws-c-mqtt, now they are.

Fix MQTT reconnect timeouts

---

awscrt/http.py
elasticurl.py
source/http.h
source/http_connection.c
source/module.c
test/test_http_client.py

H2 unittest and integration test

---

setup.py

version-bump 0.5.15

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
setup.py

Always set the package version to match the git tag when publishing

---

continuous-delivery/test-version-exists

don't check setup.py version anymore

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml

Fixed CD: get into src dir before using git

---

MANIFEST.in
codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml

Fixed CD version update, removed android test harness from package

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml

Fixed sed replacement in CD scripts

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml

Fix sed version update

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
continuous-delivery/build-wheels-manylinux2014-arm.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
continuous-delivery/build-wheels-osx.sh
continuous-delivery/build-wheels-win32.bat
continuous-delivery/build-wheels-win64.bat
continuous-delivery/update-version.py

Added python script to do version update, called from all platform builds

---

continuous-delivery/update-version.py

Setup.py update fixes

---

test/test_mqtt.py

AWS IoT does weird things with session_token (aka "X-Amz-Security-Token" query param). Add test to confirm it's working.

Add test for MQTT over websockets with session_token 

---

awscrt/mqtt.py
source/mqtt_client_connection.c

https://github.com/aws/aws-iot-device-sdk-python-v2/issues/62

Surface publish and unsubscribe errors back to Python

---

source/mqtt_client_connection.c
test/test_mqtt.py

update submodules to latest pre-release

---

.builder/actions/aws_crt_python.py
.builder/actions/manylinux-ci.py
.github/workflows/ci.yml
builder.json
setup.py
source/module.c

Python 3.9 updates

---

continuous-delivery/build-wheels-manylinux2014-x86_64.sh

Fixed path to libcrypto during CD

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
continuous-delivery/build-wheels-manylinux2014-arm.sh

Fixed paths to libcrypto in CD

---

README.md

Hopefully our aarch64 wheels work now

utterly trivial changes so we can push a new release

---

setup.py

parallel builds (if cmake 3.12+)

---

awscrt/eventstream/rpc.py
source/event_stream_rpc_client_connection.c
source/event_stream_rpc_client_continuation.c
test/test_eventstream_rpc.py

Tried to infer when user wanted it to close via refcounts. This was difficult to pull off, and the strange side-effects were difficult to explain. Instead, go for the simple "you must close it" approach.

eventstream connection must be closed by user

---

setup.py
source/io.c

* Updates host resolver creation to new interface

Update to new default resolver creation function

---

awscrt/auth.py
source/auth.h
source/auth_credentials.c
source/module.c
test/test_auth.py

expose credentials expiration

---

awscrt/auth.py
awscrt/awsiot_mqtt_connection_builder.py
source/auth.h
source/auth_credentials.c
source/module.c
test/test_auth.py

python credential provider

---

awscrt/s3.py
s3_benchmark.py
source/module.c
source/s3_client.c
source/s3_client.h
source/s3_meta_request.c
test/test_s3.py

File handle from C

---

awscrt/exceptions.py

update the str of excpetion to make it more clear out side of CRT env

---

setup.py

N/A
Add license parameter to setup.py

define the license so 'pip3 show' shows the license

---

setup.py

N/A
Make license attribute match classifier value so pip emits the right output.

Change setup.py license attribute to match classifier

---

.github/workflows/ci.yml
.gitmodules
setup.py

Updating submodules to pull in latest aws-c-s3 fixes.

Updating submodules + use aws-lc for libcrypto

---

MANIFEST.in

distribute error

---

.github/workflows/ci.yml
MANIFEST.in

- put back required files from `s2n/tests`
- add CI run that confirms the source package is working

Fix broken source package

---

MANIFEST.in

Trim more files from source distribution

---

setup.py
source/mqtt_client_connection.c

Update submodules for mqtt via http proxy

---

.github/workflows/ci.yml
awscrt/s3.py
builder.json
source/s3_meta_request.c
test/test_s3.py

Non ascii file path

---

source/event_stream_rpc_client_continuation.c

While pointing out a memory-leak in another PR, I noticed I'd made the same mistake a few months back 😅

Fix possible Py_buffer leak.

---

.github/workflows/ci.yml
README.md
continuous-delivery/build-wheels-manylinux2014-aarch64.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
continuous-delivery/build-wheels-osx.sh
continuous-delivery/build-wheels-win32.bat
continuous-delivery/build-wheels-win64.bat
setup.py

remove wheel of 3.5 and add wheel for 3.9

---

awscrt/http.py
source/http_connection.c
test/test_http_client.py

* Perform SNI/server cert chain check on Windows when CA has been overridden

Windows SNI check with CA override

---

.github/workflows/ci.yml
MANIFEST.in

Fix aws-lc build.

---

.github/workflows/ci.yml
.github/workflows/lint.yml
setup.py

CI use tag image instead latest

---

elasticurl.py

latest submodules

---

setup.py

Previously, we assumed that only "universal2" builds of Python would want to build extensions as "universal2".
But apparently the "arm64" builds of Python that come on M1 machines also want to build extensions as "universal2". 

Better detection for universal2.

---

test/test_s3.py

- Fix S3 test that were broken. Long term, we should have test create and manage it's own resource

test S3 fix

---

setup.py

bring back the skip if not found

---

docs/dev/README.md
docs/dev/writing-code.md

There's more to do here, as evidenced by all the TODOs. But this is a solid start

Developer guide for writing Python code

---

docsrc/source/_static/css/custom.css
docsrc/source/conf.py

Update doc style to wrap long text in table of context

---

test/test_s3.py

Update submodules & Fix S3 Tests

---

.builder/actions/aws_crt_python.py
.github/workflows/ci.yml
awscrt/__init__.py
awscrt/websocket.py
codebuild/cd/test_prod_pypi.yml
codebuild/linux-integration-tests.sh
docsrc/source/api/websocket.rst
docsrc/source/index.rst
guides/dev/README.md
requirements-dev.txt
scripts/clean.py
source/module.c
source/websocket.c
source/websocket.h
test/test_websocket.py

WIP bindings for aws-c-http's [websocket.h](https://github.com/awslabs/aws-c-http/blob/390114bc3e3cb0a53ce57accc4f619d704cb885c/include/aws/http/websocket.h)
This PR contains `websocket.connect_client(...)`
Future PRs will contain: sending frames, receiving frames, manually closing the connection.
This PR is being merged to a `websocket` feature branch, and TODOs will be addressed before it's merged to `main`

WebSocket part 1 - connect

---

source/mqtt5_client.c

Ack packets can potentially be NULL and must be handled in bindings.

handle null ack packets in callbacks

---

awscrt/auth.py

While working on the JS bindings and looking at the X509 work I added to Python, I noticed a typo...
________

Fix X509 documentation typo

---

.github/workflows/ci.yml
crt/CMakeLists.txt

Disable AVX512 for aws-lc on old GCC

---

source/mqtt5_client.c

Fix a bug that Puback Packet was not set

---

codebuild/cd/publish_to_prod_pypi.yml
codebuild/cd/publish_to_test_pypi.yml

Copy Musl Wheels For Publish

---

test/test_auth.py

Submodule update to:
* Fix a ping issue with the 311 client
* Remove IoT Core specific validation of topics and topic filters in the 5 client

Mqtt3 and 5 fixes/updates

---

awscrt/s3.py
source/s3_client.c
source/s3_meta_request.c
test/test_s3.py

Add checksum settings for S3

---

awscrt/s3.py
continuous-delivery/test-pip-install.py
source/module.c
source/s3.h
source/s3_client.c

For t2.xlarge:
```
Is on Ec2 Instance nitro ? {} False
Instance Type = {} None
Is Optimized for System = {} False
```
For c5n.xlarge:
```
Is on Ec2 Instance nitro ? {} True
Instance Type = {} c5n.xlarge
Is Optimized for System = {} False
```
For  p4d.24xlarge:
```
Is on Ec2 Instance nitro ? {} True
Instance Type = {} p4d.24xlarge
Is Optimized for System = {} True
```

Environment Detection 2

---

.github/workflows/ci.yml

Fix freebsd python ci

---

awscrt/s3.py
source/module.c
source/s3.h
source/s3_client.c
test/test_s3.py

Binds the `aws_s3_get_platforms_with_recommended_config()`

API to get list of pre optimized systems

---

awscrt/mqtt5.py
source/mqtt5_client.c

Adds topic aliasing support to MQTT5

Topic Aliasing Support

---

awscrt/s3.py
source/s3_client.c
test/test_s3.py

Bind out mem limiter

---

awscrt/auth.py
awscrt/s3.py
source/auth.h
source/auth_credentials.c
source/auth_signing_config.c
source/s3_client.c
test/test_s3.py

Performance optimization Updates

---

source/mqtt5_client.h

Mqtt5 General Availability

---

source/event_stream_rpc_client_connection.c
source/http_connection.c
source/http_proxy.c
source/mqtt5_client.c
source/mqtt_client_connection.c
source/websocket.c

Issue: https://github.com/awslabs/aws-c-io/issues/576

To support VSOCK, stop limiting `port` to 16 bits.

---

awscrt/mqtt5.py
source/mqtt5_client.c

bind out connack_timeout_ms for mqtt5

Bind connack_timeout_ms for mqtt5

---

awscrt/mqtt5.py

Manual application of https://github.com/awslabs/aws-crt-python/pull/561

Typing fixes

---

awscrt/s3.py

Mark the network interface API experimental

---

test/test_websocket.py

```
aws-c-auth         v0.7.25 -> v0.7.28
aws-c-cal          v0.7.3 -> v0.7.4
aws-c-common       v0.9.27 ✓
aws-c-compression  v0.2.18 -> v0.2.19
aws-c-event-stream v0.4.3 ✓
aws-c-http         v0.8.8 ✓
aws-c-io           v0.14.18 ✓
aws-c-mqtt         v0.10.4 ✓
aws-c-s3           v0.6.4 ✓
aws-c-sdkutils     v0.1.19 ✓
aws-checksums      v0.1.18 -> ~v0.1.19~ Leaving checksums out, since it breaks the build for arm
aws-lc             v1.33.0 -> v1.34.2
s2n                v1.5.0 -> v1.5.1
```

Pick up the change from auth for vpc-lattice-svcs specific presign 

---

awscrt/checksums.py
source/checksums.h
source/crc.c
source/module.c
test/test_checksums.py

Bind out crc64

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
continuous-delivery/sanity-check-test-pypi.bat

- Update win sanity check script to not use python 37

Update Win Sanity Check Script 

---

awscrt/io.py
test/test_http_client.py

N/A
Use PQ Default Policy for testing

Use PQ Default Policy for testing

---

setup.py

**Issue:**
Build errors on AL2012, due to linking librt statically
**Diagnosis:**
We have a [tricky bit of code in setup.py](https://github.com/awslabs/aws-crt-python/blob/bc205fa35e28fab19cddd3b9cd506cdc031d98e9/setup.py#L351-L362) where we force SOME libraries to be linked statically. The location of this code is sensitive. Libraries added afterwards are NOT forced to be statically linked, and that's on purpose. That code was moved in a [recent PR](https://github.com/awslabs/aws-crt-python/pull/630), and now it's forcing ALL libraries to be linked statically, even ones that are always available on the OS.
* Move tricky bit of code back where it was
* Remove some old code that only applied to ancient versions of python
* Simplify some code that checks whether …

Fix build build errors on AL2012, due to linking librt statically

---

codebuild/cd/publish_to_prod_pypi.yml
codebuild/cd/publish_to_test_pypi.yml
codebuild/cd/test_prod_pypi.yml
codebuild/cd/test_test_pypi.yml
codebuild/cd/test_version_exists.yml

update comments on which images are used

---

source/crypto.c
test/test_crypto.py

Bind out pkcs8 for rsa
