awslabs/aws-crt-python

awscrt/http.py
awscrt/mqtt.py
mqtt_test.py
setup.py
source/http_connection.c
source/io.c
source/module.c
source/mqtt_client_connection.c
source/mqtt_client_connection.h
test/test_http_client.py

MQTT changes:
- added `mqtt.Connection.resubscribe_to_existing_topics()`
- `clean_session` flag is no longer ignored
- interrupted/resumed callbacks take additional `connection` arg
- Detect when server rejects the subscription
HTTP changes:
- `HttpStream.completion_future.result()` returns status_code instead of None 
Update dependencies:
- aws-c-common v0.4.12
- aws-c-io v0.4.12
- aws-c-mqtt to v0.4.9

Resubscribe

---

builder.json
elasticurl.py
setup.py
test/__init__.py
test/test_http_client.py

only `manylinux` builds are running all variants for now.
Also fix python 2

Add CI for Python 2.7, 3.4, 3.5, 3.6

---

setup.py
source/http_message.c
source/http_stream.c
test/__init__.py
test/test_http_client.py

- fix mysterious python 2 crash
- add regression test for mysterious python 2 crash
- fix actual mis-use of PyWeakref_GetObject()
- bump version#

Fix mysterious python 2 crash

---

codebuild/cd/publish_to_prod_pypi.yml
codebuild/cd/publish_to_test_pypi.yml
continuous-delivery/wait-for-pypi.py
setup.py

the way custom URLs work for `pip install` is different than how they work for `pip search`

Fix wait-for-pypi script

---

awscrt/auth.py
source/auth.h
source/auth_credentials.c
source/module.c
source/module.h
test/test_credentials.py

Previously, the `Credentials` class was pure python and I assumed we'd just copy data out as necessary.
When binding the signers I realized this was making things more complicated than if we'd just bound it directly to the `aws_credentials` struct.

Actually bind Credentials to aws_credentials

---

source/auth_credentials.c
source/auth_signer.c
source/auth_signing_config.c
source/http_connection.c
source/http_headers.c
source/http_message.c
source/http_stream.c
source/io.c
source/module.c
source/module.h
source/mqtt_client.c
source/mqtt_client_connection.c

I used to think PyObject_GetAttrString() set an exception when returning NULL, but it does not.
So go through and make sure we set an exception where necessary. This mostly effects the aws_py_get_XYZ() functions, which are super copy-pasty, so replace their implementations with helper functions/macros that have great error messages while I'm at it.

Set exception when attribute isn't found

---

awscrt/http.py

default argument values are global singletons at runtime.
This can lead to surprising results if they're modified later

remove non-trivial default args

---

awscrt/auth.py
awscrt/exceptions.py
awscrt/http.py
awscrt/mqtt.py
elasticurl.py
mqtt_test.py
source/http_connection.c
source/module.c
source/module.h
test/test_exceptions.py
test/test_http_client.py

- Example: `AwsCrtError(name='AWS_IO_SOCKET_CLOSED', message='socket is closed.', code=1051)`
- Remap to built-in python exceptions where possible (Ex: Return `MemoryError` instead of `AwsCrtError(name='AWS_ERROR_OOM')`
- In the future, I still intend to code-gen a class for each AWS_ERROR int, but this is a forwards-compatible stand-in until then (generated classes will all inherit from AwsCrtError).

AwsCrtError class instead of error_code ints

---

awscrt/awsiot_mqtt_connection_builder.py
awscrt/mqtt.py
mqtt_test.py
source/mqtt_client_connection.c
test/test_mqtt.py

- Builder functions return an MQTT Connection configured for use with AWS IoT.
- MQTT Connection() class rejiggered to be more builder-friendly. Million args are passed to constructor instead of connect().

mqtt builder

---

awscrt/http.py
awscrt/io.py
elasticurl.py
mqtt_test.py
test/test_auth.py
test/test_http_client.py
test/test_io.py
test/test_mqtt.py

Remove default arguments that resulted in heavyweight objects being created.
Yes, it's more boilerplate, but it prevents someone from accidentally creating a new EventLoopGroup with each HTTP or MQTT connection.

Explicit setup

---

awscrt/awsiot_mqtt_connection_builder.py
awscrt/mqtt.py
elasticurl.py
mqtt_test.py
setup.py
test/test_auth.py
test/test_http_client.py

No API changes here, just fixing up existing callbacks. 
- Add "forward compatibility kwargs" to callbacks that were missing it.
- Put back named args in functions that were **only** taking `(**kwargs)`. This is much nicer to read and write. This is what they Python SDK team had meant, but I didn't totally understand on the first pass.
- Ex: ~~def my_msg_cb(**kwargs)~~ -> `def my_msg_cb(topic, message, **kwargs)`

Callbacks take kwargs in the suggested manner

---

codebuild/cd/manylinux1-tee.yml
setup.py

Codebuild is killing me

---

awscrt/awsiot_mqtt_connection_builder.py
awscrt/io.py
elasticurl.py
source/auth_credentials.c
source/auth_signer.c
source/auth_signing_config.c
source/http_connection.c
source/http_proxy.c
source/http_stream.c
source/io.c
source/module.c
source/module.h
source/mqtt_client_connection.c
test/appexit_http.py
test/test_appexit.py
test/test_io.py
test/test_mqtt.py

Add tests that ensure we can shutdown cleanly with native stuff still running. Added lots of stuff to make this work and get our CI more robust.
Windows CI is now required! 🎉🎉🎉 It always passes! 🎉🎉🎉
- test_appexit.py: runs sample apps that exit with native stuff still running. Checks that exit-code is zero.
- appexit_http.py: sample app that makes an HTTP request
- TODO: mqtt sample app
- Expose EventLoopGroup shutdown to python.
- Don't acquire GIL during application shutdown. Attempting to do so will crash.
- Python 2 runs shutdown fn. It didn't used to, and the logger would raises errors during shutdown.
- Don't AWS_FATAL_ASSERT that python callbacks succeed. They often fail during shutdown.
- Increase connection timeouts to 5s by default. elasticurl and mqtt-builder used 3s, which …

Support sloppy shutdowns

---

awscrt/awsiot_mqtt_connection_builder.py

*Issue #, if available:* #123 
*Description of changes:* Standardized on ```keep_alive```, but for now, still allow ```keepalive``` for backward compatibility.

Made keep_alive consistent

---

continuous-delivery/test-version-exists
setup.py

We did a bunch of tagged releases without changing the version in setup.py.
I bumped each one up by .1 today: setup.py became 0.5.7 and the tag became v0.5.10
Those don't match.
Now they will match with the next release.
Oye.

Get version# in setup.py back in alignment with tag#

---

continuous-delivery/test-version-exists

Broke when we upgraded the docker images in our release pipeline

use python3 in release script

---

setup.py
source/io.c
test/test_auth.py

Testing this bug via an auth test, rather than a test direcly on `awscrt.io.InputStream` because we haven't added read()/seek() functions that are accessible from python. But we know that auth will seek after signing the body
Don't have a canonical Sigv4 results to check the signed request against, so this new test just checks that we don't raise an exception. Can anyone hook me up with expected signed values?

Fix bug in binding of aws_input_stream_seek()

---

awscrt/http.py
test/test_http_client.py

Fix bug where HttpRequest could be destroyed before HttpClientStream was done with it

Fix HttpRequest refcounting bug

---

source/module.c

We were seeing occasional crashes in the logger code when a program exited while native objects were still alive. The global static logger was cleaned up during module unload, so if another thread is logging in the middle of that ... crash. Attempt to fix by NOT cleaning up global statics during module unload.
It's not clear to me whether C modules can be reloaded, so this seems like an acceptable solution. If someone can show me where the reload process is documented, and has a use case, we can try harder to support it. Maybe track the number of living native objects, and clean up global statics if the count is 0.
For history's sake, here's a link where were first started supporting "sloppy shutdown" https://github.com/awslabs/aws-crt-python/pull/116
By submitting this pull request, I …

More support for sloppy shutdowns.

---

test/test_http_client.py

This test was failing pretty often.
Turns out there's a simple reason for that.

Increase timeout for test downloading 14MB file

---

awscrt/http.py
awscrt/io.py
source/io.c
test/test_io.py

AWS CLI has a custom stream class with no base that only implements read()
* Don't require python stream to inherit from `io.IOBase`
* Accept python streams that only implement `read()` (previously required `readinto()`).
* C callbacks now invoke private methods on python self, instead of public methods on other python stream. Easier to debug, and keeps complex logic out of C
* Tweak docs to clarify "binary stream" and "HTTP stream"

Accept duck typed python streams.

---

continuous-delivery/build-wheels-manylinux2014-aarch64-jenkins.sh
continuous-delivery/build-wheels-manylinux2014-x86_64-jenkins.sh

Error on Jenkins was:
> Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/aws-crt-python/continuous-delivery/build-wheels-manylinux2014-x86_64.sh\": permission denied": unknown.

attempt to fix manylinux2014 job

---

continuous-delivery/build-wheels-manylinux2014-aarch64-jenkins.sh
continuous-delivery/build-wheels-manylinux2014-x86_64-jenkins.sh

Error on Jenkins was:
> the input device is not a TTY

jenkins is not a tty

---

codebuild/cd/test_prod_pypi.yml
codebuild/cd/test_test_pypi.yml
continuous-delivery/wait-for-pypi.py

Attempt to stop this semi-regular failure in our release pipeline.

don't use cache when pulling brand new version from pypi

---

awscrt/auth.py
awscrt/http.py
awscrt/io.py
elasticurl.py
mqtt_test.py
setup.py
test/__init__.py
test/appexit_http.py
test/test_appexit.py
test/test_auth.py
test/test_http_client.py
test/test_io.py
test/test_mqtt.py

These were needed to support Python 2, but we don't support Python 2 anymore

don't need to import from __future__ anymore

---

awscrt/eventstream.py
source/event_stream.h
source/event_stream_rpc_client_connection.c
source/module.c
test/test_eventstream.py

implemented connect() and close() so far. Chose to use a handler, instead of individual callbacks, so that it's harder to create circular references that would prevent the connection from ever cleaning up.

event-stream RPC connection

---

awscrt/eventstream.py
source/event_stream.h
source/event_stream_headers.c
source/event_stream_rpc_client_connection.c
source/module.c
test/test_eventstream.py

Define headers, enums, flags, etc necessary for sending and receiving protocol messages.
2 choices made for simplicity over efficiency:
1) Rather the pass complex `EventStreamHeader` class back and forth between python and C, I always pass a simple `(name, value, type)` tuple. Transforming back and forth between them is less efficient than dealing directly with the `EventStreamHeader` class in C, but it makes the C code much simpler and less likely to leak references. We can always come back and make this more efficient in the future without affecting the public API.
2) Deep-copying contents of python headers to C headers. We could get away with non-owning references to the header names and values, but the code would be more complex. Again, we can change this under the hood without …

event-stream headers and protocol messages

---

.github/workflows/ci.yml
CONTRIBUTING.md
awscrt/eventstream.py
awscrt/eventstream/__init__.py
awscrt/eventstream/rpc.py
source/event_stream.h
source/event_stream_headers.c
source/event_stream_rpc_client_connection.c
source/event_stream_rpc_client_continuation.c
source/module.c
test/test_eventstream.py
test/test_eventstream_rpc.py

Also, some changes to the connection:
- Connection handler is now a pure abstract base class, user must store reference to connection themselves. It was weird to use the abstract-base-class stuff, but not be purely abstract
- set connection._binding from on_setup callback (instead of `connection._binding = connect()`) to avoid race condition where on_setup fires before thread calling connect() can store the binding.

Eventstream stream/continuation

---

awscrt/eventstream/rpc.py
setup.py
source/event_stream_rpc_client_connection.c
source/event_stream_rpc_client_continuation.c

- fix `setup.py` so that eventstream modules get installed
- fix crash when `eventstream.rpc.ClientConnection` was GC'd during `on_connection_shutdown` callback
- change default args to always be `=None`, so that it's easy to pass along defaults from wrapper functions
- centralize logic that sanitizes message args going in each direction between C <-> Python

eventstream fixes

---

source/event_stream_rpc_client_connection.c
source/event_stream_rpc_client_continuation.c
source/module.c
source/module.h
test/test_eventstream_rpc.py

No actual behavior changes, just code improvements
- when exceptions in setup callback close connection, use new  AWS_ERROR_CRT_CALLBACK_EXCEPTION code instead of AWS_ERROR_UNKNOWN
- add test that exceptions in setup callback close connection
- add deadlock regression test

more eventstream tests

---

awscrt/mqtt.py
awscrt/s3.py
mqtt_test.py
source/mqtt_client_connection.c
source/s3_meta_request.c
test/test_mqtt.py
test/test_s3.py

Users can now know the `qos`, `retain`, and `dup` of received messages.
This is a backwards-compatible change.

MQTT on-message callback takes more args

---

builder.json
codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
continuous-delivery/build-wheels-manylinux2014-aarch64.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
setup.py

Now that we build our own libcrypto from the aws-lc submodule, we don't need this stuff for finding a pre-installed version

Remove some old libcrypto cruft

---

setup.py

Raspberry Pi was running out of memory compiling aws-lc

limit cmake parallelism

---

source/s3_meta_request.c
test/__init__.py
test/test_s3.py

- During the on_done callback, which will be invoked as meta request finishes, the caller may touch the input stream file. Eg: `aws s3 mv foot.txt s3://bucket`. Windows will block it.
- We don't need the input stream as meta request finishes, close it earlier 
- Copy/Paste a file helper from https://github.com/boto/s3transfer/blob/develop/tests/__init__.py#L153. Since we may need it later

close input stream when meta request finishes

---

setup.py

aws-lc uses codegen to create some of its source files, and it runs these generators if the user's machine has Go and Perl installed. However, up-to-date versions of the generated files are already committed to the repo, so it's not necessary for users to run codegen on their machines.
Disabling codegen should fix the awscrt package on piwheels.org, which compiles wheels for Raspberry Pi. The piwheels build machines have Go installed, but prevent git from making network calls during the build process, and Go uses git to fetch dependencies, and .... man it took a while to figure out what was going wrong there.
Anyway, turn off the unnecessary complexity.

Don't run aws-lc's codegen at build time.

---

source/event_stream_rpc_client_connection.c
test/test_eventstream_rpc.py

* When a connection setup error has occurred, native connection is null so acquire() shouldn't be invoked

Fixing null pointer bug when connection setup error occurred.

---

source/io.c
source/s3_meta_request.c

Bizarre behavior on 32bit Raspberry Pi OS when aws_input_stream_seek() was called, due to aws-c libraries not being compiled with Large Files Support (LFS), which led to confusion over the size of off_t, which led to stack corruption when functions took arguments of this type.
This incorporates fixes from https://github.com/awslabs/aws-c-common/pull/808 and https://github.com/awslabs/aws-c-io/pull/386.  
int64_t is now used for offsets instead of off_t/aws_off_t.

Improved Posix Large File Support

---

MANIFEST.in

Fixes come from updating to latest submodules:
aws-c-io: v0.10.4 -> v0.10.5
aws-lc: 690175e -> d0a5455

Fix SNI check when custom root-CA used on Apple devices.

---

test/appexit_http.py

If we called sys.exit() from a callback on the event-loop thread, then a timeout could happen on the main thread. Not 100% sure whey this wasn't an issue in the past.

fix appexit test

---

.builder/actions/aws_crt_python.py
.github/workflows/ci.yml
README.md
codebuild/linux-integration-tests.sh
test/__init__.py
test/test_mqtt.py
test/test_proxy.py
test/test_s3.py

ISSUE: Previously, if a test needed user-specific configuration to run, it would pull things like keys and certs from AWS secretsmanager using boto3. This meant developers that wanted to run the tests locally needed to configure their AWS account exactly like the test expected (inconvenient) or use the dev-team's credentials (kinda dangerous).
DESCRIPTION OF CHANGES: Use environment variables to pass things like certs and key. When CI runs, it still pulls the values from secretsmanager, and sets env-vars accordingly. But ordinary developers can just use env-vars.

Tests use env vars so they're easier to run locally

---

.builder/actions/aws_crt_python.py
.github/workflows/ci.yml
setup.py

I discovered that the "windows-vc14 (x86)" CI run was neither x86, nor using vc14. Change it so we actually use x86 python for the x86 runs. I can't figure out how to force an older compiler though, so let's just use whatever python picks by default
Some environments failed due to installing `boto3` and then trying to use it, without restarting the python application. So use AWS CLI instead, since we know that's installed everywhere that the builder runs.
Usually python automatically sets the `-pthreads` linker flag for you, but this week it wasn't doing that on our manylinux2014-aarch64 docker images. I didn't 100% get to the bottom of why this is suddenly happening, but googling around found evidence of other python extensions [tackling this same …

Fix CI failures

---

awscrt/_test.py
awscrt/auth.py
awscrt/eventstream/rpc.py
awscrt/http.py
awscrt/io.py
awscrt/mqtt.py
awscrt/s3.py
test/test_io.py
test/test_mqtt.py

These changes make it where it's not required to create and manage a DefaultHostResolver, EventLoopGroup, or ClientBootstrap to make a connection. Instead, default singletons have been added to handle this use case.
The constructors of several classes have also been altered to allow passing a ClientBootstrap to be optional rather than required. When optional, the ClientBootstrap singleton will be used.
The MQTT connection class will free the singletons if no ClientBootstrap is passed, making the samples not require creating or directly referencing the ClientBootstrap at all.
Finally, the singletons were added to the testing to ensure they work as expected moving forward.
_______
*By submitting this pull request, I confirm that my contribution is made under the …

Connection builder simplification

---

awscrt/io.py
source/io.c
test/test_io.py

Add the ability to use a client certificate located in a Windows certificate store. Previously, the client certificate and private key had to be passed by filepath or file contents. With this change, certificates and keys stored on TPM devices can be used.

Support mutual TLS using a certificate from a Windows cert store

---

.github/workflows/docs.yml
make-docs.sh

Don't need a `.nojekyll` file. Jekyll does nothing anyway when you push vanilla HTML.

simplify make-docs script

---

make-docs.sh

This reverts commit 5f4a2fafd6ae3f3a58749185d5a976cb9aadd1bd.
Don't ask me why aws-crt-python's docs need this file to look right, but all the other CRT repos don't. I don't know.

Revert "simplify make-docs script (#354)"

---

continuous-delivery/build-wheels-osx.sh
setup.py

**Issue #** https://github.com/aws/aws-iot-device-sdk-python-v2/issues/286
Our `universal2` wheels are currently broken. They don't have everything they need to run on both `x86_64` and `arm64`. We only compiled our dependencies for 1 architecture. The linker was warning us about this but we never noticed.
**Description of Changes:**
When building `universal2` wheels, compile dependencies for both `x86_64` and `arm64`, then use `lipo` to glue them together into a universal binary.
Also:
- Turn on linker warnings. This could have helped us catch these problems earlier.
- Use more specific build tmp folder to prevents collisions when building for multiple python versions on the same machine.
- Properly set `MACOSX_DEPLOYMENT_TARGET`
**Alternatives Explored:**
Experimented with compiling …

Support Universal macOS Binary.

---

codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml

The release of [v0.13.10](https://github.com/awslabs/aws-crt-python/releases/tag/v0.13.10) just failed.
Failure was due to these python 3.5 calls.
Python 3.6 is our minimum supported version.

Fix release pipeline

---

.github/workflows/docs.yml
test/appexit_http.py

Our Github workflows don't have write permissions by default anymore, so be explicit.

Give docs job write permissions.

---

README.md
docs/README.md

Fixes links to the API documentation pointing to `https://awslabs.github.io/aws-crt-python` rather than `https://awslabs.github.io/aws-crt-python/api`.

Fix links to the API documentation

---

source/module.c
source/module.h
source/mqtt_client_connection.c

added aws_py_translate_py_error() and use it in mqtt_client_connection.c

added aws_py_translate_py_error() and use it in mqtt_client_connection.c

---

source/mqtt_client_connection.c

Fixes an error where Python will report it has ran out of memory (`AWS_ERROR_OOM`) when using `resubscribe_existing_topic` when a client gets disconnected and then reconnects.
________

Fix out of memory issue when resubscribing

---

.builder/actions/aws_crt_python.py
.github/workflows/ci.yml
README.md
codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
continuous-delivery/build-wheels-manylinux2014-aarch64-jenkins.sh
continuous-delivery/build-wheels-manylinux2014-aarch64.sh
continuous-delivery/build-wheels-manylinux2014-x86_64-jenkins.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
continuous-delivery/build-wheels-osx.sh
continuous-delivery/build-wheels-win32.bat
continuous-delivery/build-wheels-win64.bat
setup.py
test/__init__.py

Python 3.6 went End of Life 10 months ago (end of 2021). Drop support so we can start using sweet 3.7+ features like [dataclasses](https://docs.python.org/3/library/dataclasses.html).
Also, start building wheels for Python 3.11. I installed `3.11.0` on the Mac and Windows machines we use to build wheels, and ensured the manylinux docker images we use for Linux wheels are up to date.

Drop support for Python 3.6, add wheels for Python 3.11

---

codebuild/cd/test_test_pypi.yml
requirements-dev.txt
setup.py

**Issue:**
Mac builds take twice as long as other platforms because we compile native code for two architectures (x86_64, arm64) then merge it all into a Universal2 binary that works on both Intel and Apple Silicon.
Most of our developers use Macs, and this really kills iteration time.
When doing a "develop" build (this is only done on local machines, our CI does a normal "install" build), only build for the host architecture. This cuts build time in half.

Speed up Mac developer builds by only building 1 arch

---

crt/CMakeLists.txt
setup.py

**Issue:**
Developer iteration on aws-crt-python is slow.
We've noticed that other CRT language bindings ([Java](https://github.com/awslabs/aws-crt-java/blob/cb306b46e3738298f669086895622c3d42cb76f0/CMakeLists.txt), [NodeJS](https://github.com/awslabs/aws-crt-nodejs/blob/380028fbf21e27fa735f02b460b882a41a52a424/CMakeLists.txt), etc) build much faster.
Do like the other aws-crt-Use a root CMakeLists.txt that includes all the other dependencies. This lets us build all dependencies in parallel.
**Results:**
Approximately 2X speedup (builds in half the time)

Speed up builds by using a root CMakeLists.txt

---

awscrt/websocket.py
source/websocket.c
test/test_websocket.py

See part 1 here: https://github.com/awslabs/aws-crt-python/pull/411
This PR contains:
- `on_connection_shutdown` is hooked up
- `WebSocket.close()` is hooked up

WebSocket part 2 - shutdown

---

awscrt/mqtt5.py
source/module.c
source/mqtt5_client.c

**Issue:**
Mysterious crashes due to using the wrong letter when passing variables between C and Python.
**Background:**
Python's c-api uses [misc letters](https://docs.python.org/3/c-api/arg.html) to indicate various integer types. This way of passing args slips through C's type-checking mechanisms and it's easy to get things wrong, the compiler won't warn you.
Also, the Python docs refer to old-school C type names like `unsigned short`. Our AWS C code usually uses the less-confusing fixed-width sizes like `uint16_t`. But it gets confusing when you need to cross-reference against the python docs.
- Fix (hopefully) everywhere we got an int type wrong
- Cast integers to the type we expect, so the compiler warns us if we accidentally have a "narrowing" error
- …

Fix mqtt5 code using wrong letter to pass int types

---

source/http_stream.c

In the http stream bindings, the overall cursor is always a safe bound for the individual name value pair pieces.

Convert from strlen to strnlen where it's safe and reasonable to do so

---

source/io.c

This wasn't causing any real world problems since all the enum values fit in 1 byte, but it's not the right way to pass an enum from python -> C.

Fix bug passing enum value from python to C as a byte instead of int

---

awscrt/io.py
source/io.c
source/io.h
source/module.c
test/test_crypto.py
test/test_http_client.py
test/test_io.py

N/A
Add Option to configure Hybrid PQ TLS Cipher Preferences. 
Note: I don't write a lot of Python, and this is the first time I'm writing Python-to-C translation code, so please take an extra close look when reviewing to make sure I didn't make any simple mistakes. 

Add Option to configure Hybrid PQ TLS Cipher Preferences

---

awscrt/websocket.py
source/websocket.c
test/test_websocket.py

Related: https://github.com/awslabs/aws-c-http/pull/409

Failed WebSocket handshake response now includes body

---

awscrt/websocket.py

**Issue:**
If user called `sys.exit()` from a WebSocket callback, the program would exit non-gracefully, printing out a big old C stack trace.
**Diagnosis:**
The websocket callbacks are doing some [extra zealous error checking](https://github.com/awslabs/aws-crt-python/blob/edf0ef624bd84ab6d669b9b8639e2d9a43140c95/source/websocket.c#L246-L250) when calling from C->Python. The Python code is supposed to catch and handle any exceptions resulting from the user's code. C will murder the applications if any other exceptions leak back to C, with the thinking that these must result from bugs in OUR code, so best to just die.
Anyway, `sys.exit()` results in a `SystemExit` exception, which inherits from`BaseException` instead of `Exception`, so it was slipping through the Python code's `except …

Handle user calling sys.exit() from WebSocket callback

---

awscrt/mqtt.py
source/module.c
source/mqtt_client_connection.c
source/mqtt_client_connection.h
test/test_mqtt.py
test/test_mqtt5.py

Adds operation statistics support to `aws-crt-nodejs` for MQTT311. Also adds operation statistics support tests for both MQTT311 and MQTT5 to increase code coverage and safety.
~~Relies on https://github.com/awslabs/aws-c-mqtt/pull/247 being merged and released.~~
__________

Mqtt311 operation statistics support

---

awscrt/mqtt.py
awscrt/mqtt5.py
source/mqtt5_client.c
source/mqtt_client_connection.c
test/test_mqtt.py
test/test_mqtt5.py

Adjusts operation statistics getting functions in both MQTT311 and MQTT5 to return the statistics directly rather than via a future.
_____________

Remove future from operation statistics

---

awscrt/io.py
source/io.c

The documentation for the PKCS11 `create_client_with_mtls_pkcs11()` function states that you can pass `None` as a valid input, but this is not allowed because `user_pin` is not set to `None` by default. When using Python with typing, this causes problems.
This PR fixes that by making the `user_pin` optional by setting it to `null` by default. It also adjusts the C code to check if the value is `null` and, if it is, it passes a zeroed out `aws_byte_cursor`.
___________

Allow passing None for the PKCS11 user pin

---

setup.py

This doesn't fully address, but is needed to support #447.
OpenBSD doesn't ship with librt (anything needed from librt should be found in libc). 
With this PR and the changes detailed in #447, the Python bindings build and are usable on OpenBSD.

Fix linking on OpenBSD

---

source/http_connection.c

The result object is decref'd immediately after the call to `PyObject_CallFunction()`, do not decref it again.
This fixes `Fatal Python error: deallocating None` when running the test suite with the module built for Python 3.11 on Fedora.

Do not decref the result object twice

---

test/test_s3.py

Remove 10mb file that we used for testing puts and replace it with temp file generated on the fly

Generate s3 test file instead of checking it into source

---

MANIFEST.in

By default, only files matching the test/test*.py pattern are included in source distribution. This leaves the test suite unusable, because resources and some necessary scripts are missing.
Fix that.
Fixes #281.

Include the entire test suite in source distribution

---

awscrt/auth.py
source/auth.h
source/auth_credentials.c
source/module.c
test/test_proxy.py

Binds X509 support to the Python AWS credentials provider and adds the tests to make sure it works as expected (modeled tests to be like those in Java).
________

X509 binding

---

crt/CMakeLists.txt

**Issue #:** https://github.com/awslabs/aws-crt-python/issues/457
Be sure to set build options in a way that works with older CMake

Fixes for CMake 3.12 and older

---

.github/workflows/ci.yml
README.md
crt/CMakeLists.txt
setup.py

original: https://github.com/awslabs/aws-crt-python/pull/454
- Use `AWS_CRT_BUILD_USE_SYSTEM_LIBCRYPTO` as the env var name instead
- Added CI

Add AWS_CRT_BUILD_USE_SYSTEM_LIBCRYPTO

---

setup.py

This hack was an attempt to work around a long-standing bug where we had our include-paths and linker-paths in the wrong order. This was fixed in https://github.com/awslabs/aws-crt-python/pull/455 so we don't need the hack anymore.

Remove linker hack

---

setup.py

**Issue:**
"Remove linker hack (#462)" caused internal Amazon devs to start having issues building Lambda applications.
**Investigation:**
In Amazon's internal build system, dependencies are built as both static and shared libs. "Remove linker hack (#462)"  resulted in a switch from using static libs, to using the shared libs.
Lambda applications need all their runtime dependencies explicitly packaged up. The switch to use shared libs meant devs needed to add a lot more runtime dependencies.
Put back code that forces dependencies to be linked statically, to keep things simple and minimize runtime dependencies.

Revert "Remove linker hack (#462)". Always link dependencies statically.

---

awscrt/mqtt.py

Helps fix https://github.com/aws/aws-iot-device-sdk-python-v2/issues/420 by documenting the behavior of the resubscribe function.
Adds documentation on the limits of the resubscribe function in relation to the AWS IoT Core limits.
___________

Add note about resubscribe limits to api docs

---

.github/workflows/ci.yml
builder.json
continuous-delivery/build-wheels-manylinux2014-aarch64.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
continuous-delivery/build-wheels-musllinux-1-1-aarch64-jenkins.sh
continuous-delivery/build-wheels-musllinux-1-1-aarch64.sh
continuous-delivery/build-wheels-musllinux-1-1-x86_64-jenkins.sh
continuous-delivery/build-wheels-musllinux-1-1-x86_64.sh
continuous-delivery/build-wheels-osx.sh

- Adds wheel for musllinux aarch64 and x64.

MuslLinux Wheels

---

awscrt/s3.py
source/s3_client.c
source/s3_meta_request.c
test/test_s3.py

- S3 configurations now takes signing config for more control of the signing process.

S3 take sign config

---

source/mqtt_client_connection.c
test/test_mqtt.py

Expose the new on_connection_success and on_connection_failure aws-c-mqtt callbacks.

Use on_connection_* callbacks from aws-c-mqtt

---

source/mqtt_client_connection.c
source/s3_meta_request.c

**Issue:**
A user experienced random downloads hanging. I looked at their code and saw that an exception in their completion callback could lead to a hang, since later code was never executed. Then I looked at our code and saw a theoretical place where the same kinda thing could happen, an error could prevent us invoking the completion callback.
- Always invoke the completion callback, even if we failed to turn the error_response_headers into PyObjects. These headers are optional anyway.
- Use nice new error code AWS_ERROR_FILE_WRITE_FAILURE if file write fails.
- Raise error if file close fails, because that probably means it failed to flush the buffers to disk.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Improved error-handling in S3 completion callback

---

source/s3_meta_request.c
test/test_s3.py

**Issue:**
I discovered that, if you drop the reference to an S3Request before the operation completes and it's downloading using `recv_filepath`, then everything looks like it succeeds but you end up with a 0 byte file on disk.
Ensure the file isn't closed until the operation is complete.
Most of our code was careful to keep things alive until the operation was complete. But for whatever reason we put the file-closing code in the wrong place.

Fix bug when S3Request is GC'd before download completes

---

source/s3_client.c
source/s3_meta_request.c
test/test_s3.py

- Remove the hack we did in the bindings for progress callback and filepath
- We still haven't support recv_filepath from aws-c-s3 yet, so keep that
- Refactor the tests to be a bit nicer, as it was really confusing (sorry I wrote the old code, and I don't like it anymore. And it may still be confusing, I only updated the code around put object.)
- add tests fro unknown content length

Update the binding to use features from aws-c-s3

---

awscrt/s3.py
source/s3_client.c
source/s3_meta_request.c
test/test_s3.py

expose S3 multipart-threshold, and status-code for errors

---

awscrt/s3.py
source/module.c
source/s3.h
source/s3_client.c
test/test_s3.py

Bind out cross-process lock with unit tests.

---

awscrt/s3.py
source/auth_credentials.c
source/s3_client.c
test/test_s3.py

**Issue:**
The exceptions delivered from the S3Client were lacking information like the HTTP response code, headers, & body. You could get the extra information from the `on_done` callback, but it would be nice to get it from the exception, so you could use the `request.finished_future` instead of the `on_done` callback if you wanted.
Add new error type: `awscrt.s3.S3ResponseError`, which inherits from `awscrt.exceptions.AwsCrtError`. If we have information about the failed request, then use an `S3ResponseError` instead.
Debatable:
- Should this live in `awscrt.exceptions` or `awscrt.s3`?

S3ResponseError

---

awscrt/s3.py
source/s3_meta_request.c
test/test_s3.py

- Store callback exceptions in S3 on_headers and on_body callback so that we rethrow it in the on_done callback.

Store Exception for on headers and onbody callback

---

builder.json
setup.py
source/mqtt5_client.c

Previously, we only checked for C compiler warnings when doing a local "development" build (`pip install --editable .`). Now, we also check in CI.

CI checks for C compiler warnings

---

awscrt/s3.py
source/s3_meta_request.c
test/test_s3.py

This hooks up functionality from:
https://github.com/awslabs/aws-c-s3/pull/377
**Issue:**
If an AWS SDK is using the CRT S3 client, it was difficult to map CRT exceptions to SDK exceptions since it wasn't clear exactly which S3 HTTP request failed (A CRT S3 request might make several HTTP requests under the hood)
- Expose operation_name in the S3ResponseError.
- Also, if user is creating a DEFAULT request (where CRT doesn't know which operation is being performed), the user can pass in the operation_name

Add S3ResponseError.operation_name 

---

test/__init__.py
test/test_http_client.py

https://github.com/awslabs/aws-crt-python/issues/535
increase timeout for tests because of low performance devices

Test timeout increase

---

awscrt/mqtt5.py

Unsuback reason code changed from TOPIC_NAME_INVALID -> TOPIC_FILTER_INVALID 

error code fix

---

setup.py

https://github.com/awslabs/aws-crt-python/discussions/551
Looking at other Python packages with C extensions, such as [Numpy](https://pypi.org/project/numpy/), [cryptography](https://pypi.org/project/cryptography/), and [scikit-learn](https://pypi.org/project/scikit-learn/), they specify the supported operating systems rather than stating OS independent. Since `crt-python` includes C extensions and the distribution for one platform will not work on another, this PR updates the documentation to avoid confusion.

Add Specific OS Classifiers in Setup.py

---

.github/workflows/ci.yml
.github/workflows/docs.yml
awscrt/mqtt.py
awscrt/mqtt5.py
source/mqtt5_client.c
source/mqtt_client_connection.c

https://github.com/awslabs/aws-crt-python/issues/562

Pass CRT error, if it exists, into completion function

---

test/test_http_client.py

**Issue:**
awscrt.s3.S3Client is occasionally seeing errors when the server sends an HTTP response with a `Connection: close` header (meaning it intends to close the connection after the response is sent). The server is sending the full response, then immediately hanging up. But the last few bytes of the response never make it to the HTTP client.
Update submodules, bringing in this fix: https://github.com/awslabs/aws-c-io/pull/642
```
aws-c-auth         v0.7.17 -> v0.7.22
aws-c-cal          v0.6.11 -> v0.6.15
aws-c-common       v0.9.15 -> v0.9.20
aws-c-http         v0.8.1 -> v0.8.2
aws-c-io           v0.14.7 -> v0.14.9
aws-c-mqtt         v0.10.3 -> v0.10.4
aws-c-s3           v0.5.7 -> v0.5.10
aws-c-sdkutils     v0.1.15 -> v0.1.16
s2n                v1.4.11 -> …
```

Fix bug where last few bytes on socket go unread

---

.github/workflows/ci.yml
.github/workflows/docs.yml
requirements-dev.txt

**Issue:**
the docs.yml job that runs on mainline has been broken for a while
- Put the required sphinx version in 1 place (requirements-dev.txt)
- sphinx 7.3+ breaks our docs, not sure why, don't have time to look into it...
- Update docs jobs to run on latest ubuntu22.04
- sphinx requires python3.9+ now, but ubuntu20.04 has python3.8

fix docs.yml

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.gitignore
setup.py

xcode 15 ships with new linker that flags duplicate rpath entries as warning and then we treat warnings as errors. unfortunately pyenv in brew ships with duplicate entries in sysconfig. lets revert back to old linker in editable mode until this is fixed. 

Fix editable build on Macs with XCode >= 15

---

.github/workflows/ci.yml

- FreeBSD 14:latest dropped python3.9, according to [here](https://www.freshports.org/devel/py-pip/) 
- install py-pip via `pkg install devel/py-pip`. https://www.freshports.org/devel/py-pip/
- install py-urllib3 via `pkg install net/py-urllib3`. https://www.freshports.org/net/py-urllib3/
- install py-awscli via `pkg install devel/py-awscli`. https://www.freshports.org/devel/py-awscli/

fix free-bsd CI

---

source/s3_meta_request.c

As we support recv filepath in C now, we can remove the extra layer we did only for python binding and pass it down to C directly. 

use the recv filepath directly from C

---

README.md
awscrt/auth.py
setup.py

*Issue #:* https://github.com/awslabs/aws-crt-python/issues/588
User wants explicit way to choose whether aws-crt-python builds its own dependencies (their source code is under `crt/`), or find them prebuilt on the system.
There's currently a secret way to do this (delete `crt/` folder, or don't sync submodules), but it's not documented.
Set `AWS_CRT_BUILD_USE_SYSTEM_LIBS=1` to explicitly disable building dependencies

AWS_CRT_BUILD_USE_SYSTEM_LIBS

---

.github/workflows/ci.yml
codebuild/cd/manylinux-x64-build.yml
codebuild/cd/manylinux-x86-build.yml
continuous-delivery/build-wheels-manylinux2014-aarch64.sh
continuous-delivery/build-wheels-manylinux2014-x86_64.sh
continuous-delivery/build-wheels-musllinux-1-1-aarch64.sh
continuous-delivery/build-wheels-musllinux-1-1-x86_64.sh
continuous-delivery/build-wheels-osx.sh
continuous-delivery/build-wheels-win32.bat
continuous-delivery/build-wheels-win64.bat
setup.py

- Disutils is deprecated, however, currently there is no alternative see: https://github.com/pypa/setuptools/issues/2806
- This PR restricts disutils dependency to Windows only
- Drop Python 3.7 as it is EOL 
- Install requirements-dev.txt in Python 3.13 since manylinux images removed it see: https://github.com/pypa/manylinux/pull/1564/files#diff-de469cc9cf8992ffaec661b4e087cfded3ec6da722072ec1fdf11f61690fd1b8R3

Fix Release Pipeline for distutils

---

setup.py

- Missed the following comment in the previous PR https://github.com/awslabs/aws-crt-python/pull/598#discussion_r1781965728.

Fix Win Import For distutils

---

.github/workflows/ci.yml
README.md
setup.py

When we dropped support for python 3.7 in https://github.com/awslabs/aws-crt-python/pull/598
we forgot to update setup.py, and the README

Finish dropping python 3.7

---

docsrc/source/api/checksums.rst
docsrc/source/index.rst

This PR updates the documentation for this package to include the functions in `awscrt/checksums.py`.
> Note: Python 3.10 is used to match what is being used in the github action that publishes docs. The existing docs fail with Python 3.12. However, that is outside the scope of this PR.
```
python -m venv venv
. venv/bin/activate
python -m pip install -r requirements-dev.txt
python -m pip install .
cd docsrc
make html
cd build/html
python -m http.server
```
**Update:** I realized there is also a `make-docs.py` script. That also worked

Add checksums to documentation

---

crt/CMakeLists.txt

This PR is the same as https://github.com/awslabs/aws-crt-cpp/pull/648
At configuration time, `s2n-tls` performs a number of feature probes against libcrypto in order to configure itself. In the current implementation of aws-crt-python build system, the correct libcrypto does not yet exist (nor are aws-lc's headers visible to the feature check, for that matter). This results in a misconfigured s2n-tls.
Unfortunately, there is no easy way to change s2n-tls to be configured at build time, because CMake standard functionality for this (`try_compile` function) can be used only at configuration time.
Build and install aws-lc into a build directory at configuration time, so libcrypto can be used by `s2n-tls`.
This PR depends on …

Prebuild aws-lc

---

awscrt/eventstream/__init__.py
awscrt/eventstream/rpc.py

`ByteString` has been deprecated in Python 3.12 and will be removed in Python 3.14. Replace it with `Union[bytes, bytearray]`.
See: https://docs.python.org/dev/deprecations/pending-removal-in-3.14.html

Remove deprecated `ByteString`

---

README.md
setup.py

**Issue:**
https://github.com/awslabs/aws-crt-python/pull/593 introduced env-var, `AWS_CRT_BUILD_USE_SYSTEM_LIBS=1`, but it didn't work unless those system libs were built statically.
**Diagnosis:**
The reason it didn't work is: there's a hack in [setup.py](https://github.com/awslabs/aws-crt-python/blob/2dae492d57b40c68839f2ecd7867bea34e6f9f1a/setup.py#L339-L348) that forces dependencies to be linked statically on Unix variants (excluding macOS). It worked when I tested on macOS because the hack isn't applied there.
The reason for the hack is: in Brazil (internal AWS build system), dependencies are available as both static and dynamic libs. But we prefer to link the static ones so that, if a python application is packaged for AWS lambda, the developer has fewer files they need to chase …

AWS_CRT_BUILD_FORCE_STATIC_LIBS

---

setup.py

Thanks @TingDaoK for discovering this copy/paste bug.
This wasn't causing any actual problems (other than longer-than-necessary build times on macos-but-not-universal2 builds of python ... which are exceedingly rare these days), but it's fixed now.

Fix macos universal2 detection in setup.py

---

.github/workflows/ci.yml

Fix comes from:
- https://github.com/awslabs/aws-c-common/pull/1182
- https://github.com/awslabs/aws-c-common/pull/1184
Updated submodules:
```
aws-c-auth         v0.8.0 -> v0.8.1
aws-c-common       v0.10.6 -> v0.10.7
aws-c-s3           v0.7.7 -> v0.7.9
aws-c-sdkutils     v0.2.1 -> v0.2.2
aws-lc             v1.41.1 -> v1.43.0
s2n                v1.5.10 -> v1.5.11
```

Fix CRC64NVME crash on machines with disabled AVX

---

.github/workflows/ci.yml
.github/workflows/lint.yml
builder.json
requirements-dev.txt

We rely on qemu to test aarch64 on x86-64 github runners. 
Qemu had a bug where they had a bug with incorrectly mapping address space. That mostly worked fine until kernel patch that increased entropy in their address randomization. TLDR; qemu likes to segfault a lot against new kernels on our aarch64 test. Solution is to switch to a different github qemu user static image that forces a latest version of qemu, that has the bug fixed.
if you want to read more - https://github.com/tonistiigi/binfmt/issues/240
in a separate issue setuptools now prefers systems version of packages, which breaks against packaging thats on the ubuntu runners by defaults, so add packaging to our deps to ensure its getting the latest version. 
By submitting this …

Fix aarch64 runners

---

codebuild/cd/publish_to_prod_pypi.yml
codebuild/cd/publish_to_test_pypi.yml

**Issue:**
We had a release fail, the `twine` error message said
> Error during upload. Retry with the --verbose option for more details
Always run with `--verbose`. This runs in a pipeline. We definitely always want to know more details. 

When uploading release with twine, pass `--verbose`

---

source/module.c

Helper functions for non-optional integers should fail if the value is None

---

MANIFEST.in
continuous-delivery/update-version.py
crt/CMakeLists.txt

- To reduce the package size as much as possible.
1. strip more unneeded source from sdist, the specially one is `crt/aws-lc/**/crypto_test_data*`, which is [here](https://github.com/aws/aws-lc/blob/main/generated-src/crypto_test_data.cc.tar.bz2), a 40MB zip file used for tests :) 
2. use `g1` for debug symbol, which reduces the size to almost half
```
total 323.6 MB
drwxr-xr-x 2 root root    4.0 KB Apr 28 20:02 .
drwxr-xr-x 4 root root   40.0  B Apr 28 20:02 ..
-rw-r--r-- 1 root root    3.1 MB Apr 28 20:02 awscrt-0.27.0-cp310-cp310-macosx_10_15_universal2.whl
-rw-r--r-- 1 root root    8.3 MB Apr 28 20:02 awscrt-0.27.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
-rw-r--r-- 1 root root    8.5 MB Apr 28 20:02 …
```

reduce the package size

---

awscrt/__init__.py
awscrt/mqtt_request_response.py
docsrc/source/api/mqtt_request_response.rst
docsrc/source/index.rst

* Adds sphinx doc configuration for the mqtt_request_response module.
* Fixes a few doc string location issues

Request response doc config

---

.github/workflows/ci.yml

Currently, Windows CI jobs are failing with error:
```
Failed to run C:\\hostedtoolcache\\windows\\Python\\3.8.10\\x64\\python.exe -m venv D:\a\aws-crt-python\aws-crt-python\aws-crt-python\.venv-builder: Command exited with code 1
```
This is caused by recent changes in GitHub runner images: https://github.com/actions/runner-images/pull/12356
- Use Python 3.10.11 in Windows CI jobs.
- Ensure Python is installed with `actions/setup-python` (windows-2025 doesn't have x86 Python by default)

Update python version in windows CI

---

pyproject.toml
setup.py

It was added in setuptools 70.1 and this project already pins >= 75.3.1.

Use bdist_wheel from setuptools

---

test/__init__.py
test/test_mqtt.py
test/test_mqtt5.py
test/test_mqtt5_credentials.py
test/test_mqtt5to3_adapter.py
test/test_mqtt_credentials.py
test/test_mqtt_request_response.py

* Adds retry wrapper around all MQTT tests that require connectivity.  Socket and TLS negotiation timeouts are retried.
* Fixes a few tests that appear to be using the wrong helper function (will correlation data)

Retry timeouts

---

source/module.c

Prevent some crashes when misusing the logging setup API.  It is still not safe to multi-init from different threads, but this is an incremental improvement over the previous state.
https://github.com/awslabs/aws-crt-python/issues/685

Improve log init
